sudo: required

services:
  - docker

env:
  - distribution: debian
    version: buster
  - distribution: ubuntu
    version: bionic
  - distribution: ubuntu
    version: focal

before_install:
  - 'sudo docker pull ${distribution}:${version}'
  - 'sudo docker build --no-cache --file=travis/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible travis'

script:
  - container_id=$(mktemp)
  - 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/etc/ansible/roles/ansible-role-ghost-restore:ro ${distribution}-${version}:ansible > "${container_id}"'
  - 'sudo docker exec -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY "$(cat ${container_id})" ./run-tests.sh'
  - 'sudo docker rm -f "$(cat ${container_id})"'
