sudo: required

services:
  - docker

env:
  - distribution: debian
    version: buster
  - distribution: ubuntu
    version: bionic
  - distribution: ubuntu
    version: focal

script:
  - 'cd travis && sudo ./prepare.sh'
