ARG DISTRIBUTION
FROM $DISTRIBUTION

RUN apt-get update -y && DEBIAN_FRONTEND="noninteractive" apt-get install -y \
    ca-certificates \
    gnupg2 \
    openssh-server \
    python3-apt \
    python3-pip

ARG PORT
RUN sed -i 's/#PermitRootLogin/PermitRootLogin/;s/#Port 22/Port '$PORT/ /etc/ssh/sshd_config \
 && mkdir -p /root/.ssh && mkdir -p /run/sshd \
 && chmod 700 /root/.ssh

ADD testmachine.pub /root/.ssh/authorized_keys

ENTRYPOINT ["/usr/sbin/sshd", "-D"]
