FROM debian:buster

RUN apt-get update -y && apt-get install -y \
    ca-certificates \
    gnupg2 \
    openssh-server \
    python-apt \
    python-pip \
 && rm -rf /var/lib/apt/lists/*
RUN sed -i 's/#PermitRootLogin/PermitRootLogin/;s/#Port 22/Port 2222/' /etc/ssh/sshd_config \
 && mkdir -p /root/.ssh && mkdir -p /run/sshd \
 && chmod 700 /root/.ssh

ADD testmachine.pub /root/.ssh/authorized_keys

ENTRYPOINT ["/usr/sbin/sshd", "-D"]
