FROM ubuntu:bionic

ADD run-tests.sh .

RUN apt-get update && apt-get dist-upgrade -y && apt-get install -y systemd && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y \
    git \
    libffi-dev \
    libssl-dev \
    python3-pip \
    python3-venv \
 && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /etc/ansible && echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

ENTRYPOINT ["/bin/systemd"]
