FROM ubuntu:xenial

RUN apt-get update && apt-get dist-upgrade -y \
 && apt-get install -y \
       git \
       python \
       curl \
 && curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py \
 && python get-pip.py \
 && pip install --upgrade setuptools virtualenv \
 && pip install ansible ansible-lint \
 && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /etc/ansible && echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

ENTRYPOINT ["/sbin/init"]
