FROM debian:buster

ADD run-tests.sh .

RUN apt-get update -y && apt-get install -y \
    build-essential \
    gnupg2 \
    libffi-dev \
    libssl-dev \
    python3-dev \
    python3-pip \
    python3-venv \
    git \
    procps \
    systemd \
 && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /etc/ansible && echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

ENTRYPOINT ["/bin/systemd"]
